[project]
name = "get-audio-yt"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ollama>=0.5.3",
    "openai-whisper>=20250625",
    "yt-dlp>=2025.8.11",
]

[tool.uv]
native-tls= true
